### ISSUE TITLE
Refactoring mask.py code

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/DeltaMetrics#10]
Per some of the discussion in #7, there is a need to refactor some of the masking code.

Some suggestions from @amoodie in #7: 

> as we have discussed, I think that there may be a simpler way to setup the whole masking ops. A lot of repetitive code and try-excepts to determine types of inputs and then create the necessary lower-level masks (e.g. WetMask and LandMask) before being able to create an EdgeMask could be eliminated by forcing specific lower-level mask types to be the inputs. For example, make the only arguments acceptable to EdgeMask.__init__ one WetMask and one LandMask (or a single WetMask?). Then, the only acceptable input to WetMask.__init__ is a LandMask, etc. I think there would be some magic to do with the static methods then too, where each xMask has a from_eta static method, to create that xMask that would be a chain of the relevant lower-level masks.

There is also room to make the shoreline detection method more flexible. There is currently a built-in assumption of some *land width* in the input (like DeltaRCM) and automated trimming of the data prior to masking is reliant on this assumption (Lines [101](https://github.com/elbeejay/DeltaMetrics/blob/dc2ab7792a9842f10426dfe45a17d2481c9c6f3f/deltametrics/mask.py#L101) to [109](https://github.com/elbeejay/DeltaMetrics/blob/dc2ab7792a9842f10426dfe45a17d2481c9c6f3f/deltametrics/mask.py#L109)). It would be good to find an alternative solution so that these methods work for non-DeltaRCM data as well.

**Comment by amoodie** [comment]
This is resolved since #44.
