### ISSUE TITLE
MPM binary_closing

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/DeltaMetrics#142]
I was messing around with the MPM because it was very slow on a large domain. 

https://github.com/DeltaRCM/DeltaMetrics/blob/999bbe9bbeab79f63ab0fd1fc8947d81eaff25d2/deltametrics/plan.py#L1771-L1775

@elbeejay (sorry I think you wrote this bit) Am I correct in reading the lines here that the image input to binary dilation is not changed on each iteration? This seems like a bug?

**Comment by elbeejay** [comment]
Yes, looking with fresh eyes it does seem like this loop will never resolve short of hitting the iteration limit. But given that we iterate through the disk sizes in the public function, I'm struggling to remember why iterations here were ever <s>needed</s> wanted - seems like it'd be simpler to just call the binary closing function once and be done (in which case why use a private function at all).
