### ISSUE TITLE
Masks currently locked to sea level == 0

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/DeltaMetrics#20]
Are masks currently locked to sea level == 0? I think they might be. This should be relaxed, at least with an option to specify during mask creation. 

related to #10. Should consider how we will include boundary conditions in an overhaul of the netcdf file output from pyDeltaRCM too.

**Comment by elbeejay** [comment]
Am looking at the masks a bit now and wanted to note that this issue is a bit misleading. Right now the topographic threshold for defining the delta 'platform' is an optional input to the masking functions as the keyword argument `topo_threshold`.

Clearly this should be better explained in the documentation, maybe even formulated differently in the code.

**Comment by amoodie** [comment]
I see. I guess I was thinking that `topo_threshold` was more like a `topo_tolerance`, because it took a value of `-0.5` rather than `0`. So in my head, sea level was `0` and the `topo_threshold` was half a meter below whatever sea level was.

Would changing this to use `topo_threshold = sea_level + topo_tolerance` make sense? Is that more confusing?

**Comment by elbeejay** [comment]
> Would changing this to use `topo_threshold = sea_level + topo_tolerance` make sense? Is that more confusing?

I think that would be nice. Right now we don't keep sea level information as part of pyDeltaRCM (I think?), so this might be something we want to wait on until we've sorted the variables/coordinates in the netCDF file. 

Or we could come up with some method to estimate the sea level through time given the water depths or something which wouldn't be terrible, might just be less generic than a method that uses a defined variable/coordinate.

**Comment by amoodie** [comment]
This is resolved since the merge of #44.

Making many masks (any that require a datum for sea-level) now explicitly require the `elevation_threshold` argument.
