### ISSUE TITLE
Update pyDeltaRCM example datasets

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/DeltaMetrics#49]
Our sample dataset is deprecated, and with new breaking changes to the pyDeltaRCM project (namely removing `strata_` grids and creating `sand_frac`), the example "golf" sample dataset is now also deprecated.

Once we've finalized pyDeltaRCM (maybe when we hit v2?) and feel that the output is going to be consistent for some time, we should update these sample datasets...

**Comment by amoodie** [comment]
I updated to a new dataset (still called `golf`) in #69, and updated the userguide and documentation in most places to use this new cube in #74.
