### ISSUE TITLE
Negative Channel Widths

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/DeltaMetrics#65]
Need to do more to document this and get to the root cause, but wanted to flag the issue. It appears as if the `compute_channel_width` function can return negative width values. 

The image below shows a binary channel map with a circular section shown in red. Computing channel widths along this section returns the following list of channel widths: 

```
array([-230.96551211,    5.        ,    4.        ,    3.41421356,
          2.41421356,    2.41421356,    1.41421356,    5.82842712,
          3.41421356,    3.        ])
```

![image](https://user-images.githubusercontent.com/1770513/132540586-d9c46be6-a4ec-48e9-bf94-a81f1f40d01b.png)

We know channels cannot have negative widths, so therefore this is a bug.

**Comment by amoodie** [comment]
Hm, maybe it is wrapping around the back of the inlet (like the *other* half of the circular section), if both edge-pixels are channels. Would that make sense as `pi*r` for the section radius size? I'll have to look at the implementation

**Comment by elbeejay** [comment]
> Hm, maybe it is wrapping around the back of the inlet (like the _other_ half of the circular section), if both edge-pixels are channels. Would that make sense as `pi*r` for the section radius size? I'll have to look at the implementation

Internally if the `_channelstarts` array includes an index value of zero, then when the widths are calculated as:

```
_channelwidths = section_coord[_channelends-1] - section_coord[_channelstarts-1]
```

the "wrap-around" to the other side of the coordinate array takes place and allows a negative width to be calculated.
